apiVersion: v1
kind: Service
metadata: 
  name: goviolin-service
spec: 
  selector:
    app: goviolin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 #this is the port for external ip address that you will type into your browser

#Service is CDR to attach a permanent ip address to each pod
# Even if the pod dies, the service ip is the same 
# You can define internal service to block eternal requests